# استخدام نسخة بايثون رسمية وخفيفة الوزن
FROM python:3.10-slim

# تحديد مجلد العمل داخل الحاوية
WORKDIR /app

# نسخ ملف المكتبات وتثبيتها
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# نسخ بقية كود التطبيق إلى الحاوية
COPY . .

# تحديد المنفذ الذي سيعمل عليه التطبيق
EXPOSE 5000

# الأمر التشغيلي للتطبيق
CMD ["python", "app.py"]